#!/bin/bash

# Updating the Linux distro and install web server.
sudo apt update && apt upgrade -y
sudo apt install apache2 -y
echo "This is test server" > /var/www/html/index.html
sudo service apache2 start

# Add Docker's official GPG key:
sudo apt-get update
sudo apt-get install ca-certificates curl
sudo install -m 0755 -d /etc/apt/keyrings -y
sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
sudo chmod a+r /etc/apt/keyrings/docker.asc

# Add the repository to Apt sources:
echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
  $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
  sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
sudo apt-get update

#To install the latest version
sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin -y

#Verify that the Docker Engine installation is successful
sudo docker run hello-world

#Node exporter Configuration
docker run -d \
  --net="host" \
  --pid="host" \
  -v "/:/host:ro,rslave" \
  quay.io/prometheus/node-exporter:latest \
  --path.rootfs=/host

#Configuring your Prometheus instances
echo "global:
  scrape_interval: 5s
  external_labels:
    monitor: 'node'
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['127.0.0.1:9090'] ## IP Address of the localhost
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['127.0.0.1:9100'] ## IP Address of the localhost" > /opt/prometheus.yml

#run the docker for prometheus
docker run -d \
    -p 9090:9090 \
    -v /opt/prometheus.yml:/opt/prometheus.yml \
    prom/prometheus

#run the docker for grafana
docker run -d --name=grafana -p 3000:3000 grafana/grafana

echo "Operation Completed"
echo "prometheus is available on http:\\localhost:9090"
echo "grafana is available on http:\\localhost:3000"
